version: "3.2"

services:
    # Development service
    newshub-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173"
        volumes:
            - ./src:/app/src
            - ./public:/app/public
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true

    # Production service
    newshub-prod:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
